"""Utility functions for the Article Reviewer."""

import os
from pathlib import Path
from reporter import ReportGenerator


def load_article(source):
    """Load article from file or direct text.

    Args:
        source: File path or direct text string.

    Returns:
        Article text as string.
    """
    # Check if source is a file path
    if os.path.isfile(source):
        try:
            with open(source, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            raise ValueError(f"Failed to read file {source}: {str(e)}")

    # Otherwise, treat as direct text
    return source


def save_report(report_content, output_path, cost_summary=None):
    """Save the review report to a file.

    Args:
        report_content: The report content as a string.
        output_path: Path where the report should be saved.
        cost_summary: Optional cost summary dictionary to append.
    """
    try:
        # Add cost summary if provided
        if cost_summary:
            cost_section = ReportGenerator.format_cost_summary(cost_summary)
            full_report = f"{report_content}\n\n{cost_section}"
        else:
            full_report = report_content

        # Ensure parent directory exists
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        # Write the report
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(full_report)

    except Exception as e:
        raise ValueError(f"Failed to save report to {output_path}: {str(e)}")


def validate_file_exists(file_path):
    """Validate that a file exists.

    Args:
        file_path: Path to the file.

    Returns:
        True if file exists.

    Raises:
        FileNotFoundError if file doesn't exist.
    """
    if not os.path.isfile(file_path):
        raise FileNotFoundError(f"File not found: {file_path}")
    return True


def get_file_info(file_path):
    """Get information about a file.

    Args:
        file_path: Path to the file.

    Returns:
        Dictionary with file information.
    """
    path = Path(file_path)

    return {
        'name': path.name,
        'size': path.stat().st_size,
        'extension': path.suffix,
        'absolute_path': str(path.absolute())
    }


def format_file_size(size_bytes):
    """Format file size in human-readable format.

    Args:
        size_bytes: Size in bytes.

    Returns:
        Formatted string (e.g., "1.5 KB", "2.3 MB").
    """
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} TB"


def extract_article_from_report(report_path):
    """Extract the original article from a review report markdown file.

    Args:
        report_path: Path to the review report markdown file.

    Returns:
        The original article text as a string.

    Raises:
        ValueError: If article cannot be found in the report.
    """
    try:
        with open(report_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Look for the appendix section
        appendix_marker = "## Appendix: Original Article"

        if appendix_marker not in content:
            raise ValueError(
                f"Could not find '{appendix_marker}' in the report. "
                "Make sure this is a valid review report generated by the article reviewer."
            )

        # Extract everything after the appendix marker
        appendix_start = content.index(appendix_marker)
        appendix_section = content[appendix_start:]

        # Find the code block containing the article
        # Format is: ```\n<article>\n```
        code_block_start = appendix_section.find('```\n')

        if code_block_start == -1:
            raise ValueError("Could not find article code block in appendix")

        # Skip the opening ```\n
        article_start = code_block_start + 4

        # Find the closing ```
        code_block_end = appendix_section.find('\n```', article_start)

        if code_block_end == -1:
            raise ValueError("Could not find closing code block in appendix")

        # Extract the article
        article = appendix_section[article_start:code_block_end]

        # Check for truncation marker
        if "[... article truncated for report brevity ...]" in article:
            raise ValueError(
                "The article in this report was truncated. "
                "Please use the original article file instead."
            )

        return article.strip()

    except FileNotFoundError:
        raise ValueError(f"Report file not found: {report_path}")
    except Exception as e:
        if isinstance(e, ValueError):
            raise
        raise ValueError(f"Error parsing report file: {str(e)}")
